services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faceit-discord-bot
    restart: unless-stopped
    # Let the image run as its internal 'node' user to avoid host UID/GID issues (especially on Windows)
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups  # Mount backup directory directly
    ports:
      - "8080:8080"  # Health check endpoint
    environment:
      - NODE_ENV=production
      - STARTUP_RECOVERY=${STARTUP_RECOVERY:-true}
      - STARTUP_VALIDATION_DELAY_MS=${STARTUP_VALIDATION_DELAY_MS:-30000}
      - RESTORE_BACKUP_ON_START=${RESTORE_BACKUP_ON_START:-false}
      - RESTORE_BACKUP_FILE=${RESTORE_BACKUP_FILE:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Optional: Dedicated backup service for external backup automation
  backup:
    build: 
      context: .
      dockerfile: Dockerfile.backup
    container_name: faceit-bot-backup
    restart: "no"  # Run only when explicitly started
    profiles:
      - backup  # Only start when backup profile is used
    volumes:
      - ./data:/app/data:ro  # Read-only access to data
      - ./backups:/app/backups  # Mount backup directory directly
    environment:
      - BACKUP_RETENTION_DAYS=30
      - BACKUP_SCHEDULE="0 */6 * * *"  # Every 6 hours
    depends_on:
      - bot
